### ISSUE TITLE
Functionality & Performance 

### ISSUE THREAD

**Issue by moongl4de** [JohnSasser/Portfolio#10]
- Projects/Apps button isn't working properly, page slightly moves but doesn't go anywhere

- Sluggish on mobile devices, likely from the particles in the 'Technologies' section. Try reducing the particle count or disable it for mobile devices.

**Comment by JohnSasser** [comment]
> * Projects/Apps button isn't working properly, page slightly moves but doesn't go anywhere
> * Sluggish on mobile devices, likely from the particles in the 'Technologies' section. Try reducing the particle count or disable it for mobile devices.

Thanks for the review!  I'm rebuilding it from scratch rn.
